springdoc:
  swagger-ui:
    try-it-out-enabled: true
    default-model-expand-depth: 2
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:orderdb;NON_KEYWORDS=ORDER
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /order-h2-console

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-saga-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "quick.delivery.*" # 공통 이벤트 패키지 허용
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

app:
  kafka:
    topics:
      orchestrator-order: orchestrator.order.command
      order-orchestrator-reply: order.orchestrator.reply
    groups:
      order-service: order-service-group